name: Proxy Gate CI

on:
  pull_request:
    branches:
      - main 

  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    container: python:3.11@sha256:6b023894c26ea77c602814d8b682507e1f9dd731038e25f93381b488ca9e7176
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Install dependencies
        run: pip install -r requirements-lint.txt -r requirements-test.txt -r requirements.txt
      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
      - name: Pytest
        run: make pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run integration tests
        run: make integration-test

  build_and_push:
    name: Build & Publish Docker Images
    needs:
      - lint
      - test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: APP_VERSION from tag builds
        if: github.ref_type == 'tag'
        run: |
          echo 'APP_VERSION=${{ github.ref_name }}' >> "$GITHUB_ENV"
          echo 'IMAGE_TAG=${{ github.ref_name }}' >> "$GITHUB_ENV"
          echo 'IMAGE_PUSH=true' >> "$GITHUB_ENV"

      - name: APP_VERSION from branch builds
        if: github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name == 'main'
        run: |
          echo 'APP_VERSION=${{ github.ref_name }}' >> "$GITHUB_ENV"
          echo 'IMAGE_TAG=develop' >> "$GITHUB_ENV"
          echo 'IMAGE_PUSH=true' >> "$GITHUB_ENV"

      - name: APP_VERSION from pr builds
        if: github.event_name == 'pull_request'
        run: |
          echo 'APP_VERSION=pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")-${{ github.sha }}' >> "$GITHUB_ENV"
          echo 'IMAGE_TAG=develop' >> "$GITHUB_ENV"
          echo 'IMAGE_PUSH=false' >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ env.IMAGE_PUSH == 'true' }}
          build-args: |
            COMMIT_TAG=${{ github.sha }}
            APP_VERSION=${{ env.APP_VERSION }}
            IMAGE_REF_NAME=${{ github.ref_name }}
          tags: |
            ghcr.io/digimach/proxy-gate:${{ env.IMAGE_TAG }}